apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d713c0vp3-nodejs 
  janus-idp.io/tekton: d713c0vp3-nodejs
  backstage.io/kubernetes-id: d713c0vp3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d713c0vp3-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml